- name: masquerade external traffic on eth0
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE

# todo: drop masquerading between bgp routers
- name: masquerade external traffic on eth1
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth1
    jump: MASQUERADE

- name: masquerade external traffic on eth2
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth2
    jump: MASQUERADE
  when: inventory_hostname == 'edge1'

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

- name: update pkg cache
  apt:
    update_cache: yes

- name: install bird
  apt:
    name: bird
    state: present

- name: deploy bird.conf
  copy:
    src: 'files/{{ inventory_hostname }}.bird.conf'
    dest: /etc/bird/bird.conf
  notify: restart bird

- name: start bird daemon
  systemd:
    name: bird.service
    state: started
    enabled: true

